package com.github.amrmsaraya.clock.presentation.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF6f48b2)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFecdcff)
val md_theme_light_onPrimaryContainer = Color(0xFF26005a)
val md_theme_light_secondary = Color(0xFF635a70)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFeadef7)
val md_theme_light_onSecondaryContainer = Color(0xFF1f182b)
val md_theme_light_tertiary = Color(0xFF7f525d)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffd9e2)
val md_theme_light_onTertiaryContainer = Color(0xFF32101a)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfffbfc)
val md_theme_light_onBackground = Color(0xFF1d1b1e)
val md_theme_light_surface = Color(0xFFfffbfc)
val md_theme_light_onSurface = Color(0xFF1d1b1e)
val md_theme_light_surfaceVariant = Color(0xFFe8e0eb)
val md_theme_light_onSurfaceVariant = Color(0xFF49454e)
val md_theme_light_outline = Color(0xFF7a757e)
val md_theme_light_inverseOnSurface = Color(0xFFf5eff4)
val md_theme_light_inverseSurface = Color(0xFF323033)

val md_theme_dark_primary = Color(0xFFd5baff)
val md_theme_dark_onPrimary = Color(0xFF3f0e81)
val md_theme_dark_primaryContainer = Color(0xFF572e99)
val md_theme_dark_onPrimaryContainer = Color(0xFFecdcff)
val md_theme_dark_secondary = Color(0xFFcdc2db)
val md_theme_dark_onSecondary = Color(0xFF342d40)
val md_theme_dark_secondaryContainer = Color(0xFF4b4358)
val md_theme_dark_onSecondaryContainer = Color(0xFFeadef7)
val md_theme_dark_tertiary = Color(0xFFf1b7c4)
val md_theme_dark_onTertiary = Color(0xFF4a252f)
val md_theme_dark_tertiaryContainer = Color(0xFF643a45)
val md_theme_dark_onTertiaryContainer = Color(0xFFffd9e2)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1d1b1e)
val md_theme_dark_onBackground = Color(0xFFe7e1e6)
val md_theme_dark_surface = Color(0xFF1d1b1e)
val md_theme_dark_onSurface = Color(0xFFe7e1e6)
val md_theme_dark_surfaceVariant = Color(0xFF49454e)
val md_theme_dark_onSurfaceVariant = Color(0xFFcbc4cf)
val md_theme_dark_outline = Color(0xFF948e99)
val md_theme_dark_inverseOnSurface = Color(0xFF1d1b1e)
val md_theme_dark_inverseSurface = Color(0xFFe7e1e6)

val seed = Color(0xFF7e57c2)
val error = Color(0xFFba1b1b)

val Red500 = Color(0xFFF44336)

val Purple100 = Color(0xFFF3E5F5)
val Purple200 = Color(0xFFB39DDB)
val Purple900 = Color(0xFF311B92)

val BlueGray100 = Color(0xFFECEFF1)
val BlueGray200 = Color(0xFFB0BEC5)
val BlueGray900 = Color(0xFF263238)

val Teal100 = Color(0xFFE0F2F1)
val Teal200 = Color(0xFF80CBC4)
val Teal900 = Color(0xFF004D40)

val Orange100 = Color(0xFFFBE9E7)
val Orange200 = Color(0xFFFFAB91)
val Orange900 = Color(0xFFBF360C)

val Blue100 = Color(0xFFE3F2FD)
val Blue200 = Color(0xFF90CAF9)
val Blue900 = Color(0xFF0D47A1)

val Pink100 = Color(0xFFFCE4EC)
val Pink200 = Color(0xFFF48FB1)
val Pink900 = Color(0xFF880E4F)

